### ISSUE TITLE
Do the opposite with CSS

### ISSUE THREAD

**Issue by To1ne** [lelanthran/l2h#4]
Hey,

Just want to say I love this project.

The funny thing about it, I did the opposite but purely with CSS. You can see it in action at my website https://iotcl.com/.

If you like, you're welcome to incorporate my CSS into this project, if you mention my name somewhere in the credits. 

I'm considering to rewrite my site to use your `l2h` because that would make it full circle.

**Comment by lelanthran** [comment]
Thank you for your kind words. Your site looks great too.

I'm closing this as an issue, though.
